Vagrant::Config.run do |config|

  # name of vagrant box
  config.vm.box = "pecl_demo"

  # bootstrap provisioning
  config.vm.provision :shell, :inline => 'sed -i "s/#prepend domain-name-servers 127.0.0.1/prepend domain-name-servers 8.8.8.8/g" /etc/dhcp/dhclient.conf && service networking start; gem list | grep chef || gem install chef --no-rdoc --no-ri; apt-get -y update'		# comment out to speed up reloads

  # upgrade chef to latest
  #config.vm.provision :shell, :inline => 'gem update chef --no-rdoc --no-ri'

  # chef-solo provisioning
  config.vm.provision :chef_solo do |chef|
    # debugging
	chef.log_level = :debug

    chef.cookbooks_path = File.join(Dir.pwd, '..', 'cookbooks')

    chef.json.merge!(JSON.parse(File.read(File.join(Dir.pwd, '..', 'examples', 'chef-solo', 'node.json'))))

    chef.run_list = JSON.parse(File.read(File.join(Dir.pwd, '..', 'examples', 'chef-solo', 'node.json')))['run_list']
    #chef.run_list = []
  end

end